// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mongodb/atlas-cli-core/transport (interfaces: ProfileProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_profile_provider.go -package=transport github.com/mongodb/atlas-cli-core/transport ProfileProvider
//

// Package transport is a generated GoMock package.
package transport

import (
	reflect "reflect"

	config "github.com/mongodb/atlas-cli-core/config"
	auth "go.mongodb.org/atlas/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileProvider is a mock of ProfileProvider interface.
type MockProfileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProfileProviderMockRecorder
	isgomock struct{}
}

// MockProfileProviderMockRecorder is the mock recorder for MockProfileProvider.
type MockProfileProviderMockRecorder struct {
	mock *MockProfileProvider
}

// NewMockProfileProvider creates a new mock instance.
func NewMockProfileProvider(ctrl *gomock.Controller) *MockProfileProvider {
	mock := &MockProfileProvider{ctrl: ctrl}
	mock.recorder = &MockProfileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileProvider) EXPECT() *MockProfileProviderMockRecorder {
	return m.recorder
}

// AuthServerMetadata mocks base method.
func (m *MockProfileProvider) AuthServerMetadata() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthServerMetadata")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// AuthServerMetadata indicates an expected call of AuthServerMetadata.
func (mr *MockProfileProviderMockRecorder) AuthServerMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthServerMetadata", reflect.TypeOf((*MockProfileProvider)(nil).AuthServerMetadata))
}

// AuthType mocks base method.
func (m *MockProfileProvider) AuthType() config.AuthMechanism {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthType")
	ret0, _ := ret[0].(config.AuthMechanism)
	return ret0
}

// AuthType indicates an expected call of AuthType.
func (mr *MockProfileProviderMockRecorder) AuthType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthType", reflect.TypeOf((*MockProfileProvider)(nil).AuthType))
}

// ClientID mocks base method.
func (m *MockProfileProvider) ClientID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientID indicates an expected call of ClientID.
func (mr *MockProfileProviderMockRecorder) ClientID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientID", reflect.TypeOf((*MockProfileProvider)(nil).ClientID))
}

// ClientSecret mocks base method.
func (m *MockProfileProvider) ClientSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientSecret indicates an expected call of ClientSecret.
func (mr *MockProfileProviderMockRecorder) ClientSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSecret", reflect.TypeOf((*MockProfileProvider)(nil).ClientSecret))
}

// OpsManagerURL mocks base method.
func (m *MockProfileProvider) OpsManagerURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpsManagerURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// OpsManagerURL indicates an expected call of OpsManagerURL.
func (mr *MockProfileProviderMockRecorder) OpsManagerURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpsManagerURL", reflect.TypeOf((*MockProfileProvider)(nil).OpsManagerURL))
}

// PrivateAPIKey mocks base method.
func (m *MockProfileProvider) PrivateAPIKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateAPIKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// PrivateAPIKey indicates an expected call of PrivateAPIKey.
func (mr *MockProfileProviderMockRecorder) PrivateAPIKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateAPIKey", reflect.TypeOf((*MockProfileProvider)(nil).PrivateAPIKey))
}

// PublicAPIKey mocks base method.
func (m *MockProfileProvider) PublicAPIKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicAPIKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// PublicAPIKey indicates an expected call of PublicAPIKey.
func (mr *MockProfileProviderMockRecorder) PublicAPIKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicAPIKey", reflect.TypeOf((*MockProfileProvider)(nil).PublicAPIKey))
}

// Save mocks base method.
func (m *MockProfileProvider) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProfileProviderMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProfileProvider)(nil).Save))
}

// ServiceAccountToken mocks base method.
func (m *MockProfileProvider) ServiceAccountToken() (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAccountToken")
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServiceAccountToken indicates an expected call of ServiceAccountToken.
func (mr *MockProfileProviderMockRecorder) ServiceAccountToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAccountToken", reflect.TypeOf((*MockProfileProvider)(nil).ServiceAccountToken))
}

// SetAccessToken mocks base method.
func (m *MockProfileProvider) SetAccessToken(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAccessToken", arg0)
}

// SetAccessToken indicates an expected call of SetAccessToken.
func (mr *MockProfileProviderMockRecorder) SetAccessToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccessToken", reflect.TypeOf((*MockProfileProvider)(nil).SetAccessToken), arg0)
}

// SetRefreshToken mocks base method.
func (m *MockProfileProvider) SetRefreshToken(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRefreshToken", arg0)
}

// SetRefreshToken indicates an expected call of SetRefreshToken.
func (mr *MockProfileProviderMockRecorder) SetRefreshToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefreshToken", reflect.TypeOf((*MockProfileProvider)(nil).SetRefreshToken), arg0)
}

// SetTokenExpiry mocks base method.
func (m *MockProfileProvider) SetTokenExpiry(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTokenExpiry", arg0)
}

// SetTokenExpiry indicates an expected call of SetTokenExpiry.
func (mr *MockProfileProviderMockRecorder) SetTokenExpiry(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTokenExpiry", reflect.TypeOf((*MockProfileProvider)(nil).SetTokenExpiry), arg0)
}

// Token mocks base method.
func (m *MockProfileProvider) Token() (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockProfileProviderMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockProfileProvider)(nil).Token))
}
